import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
import uuid

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='Announcement', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('title', models.CharField(max_length=180)), ('body', models.TextField()), ('audience', models.CharField(choices=[('ALL', 'Everyone'), ('INTERN', 'Interns'), ('HR', 'HR / Evaluators')], default='ALL', max_length=12)), ('published', models.BooleanField(default=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL))], options={'ordering': ['-created_at']}),
        migrations.CreateModel(name='Certificate', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('certificate_code', models.CharField(blank=True, max_length=40, unique=True)), ('program_title', models.CharField(default='CME Internship & Training Program', max_length=160)), ('issue_date', models.DateField(blank=True, null=True)), ('is_issued', models.BooleanField(default=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='Profile', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('HR', 'HR / Evaluator'), ('INTERN', 'Intern')], default='INTERN', max_length=10)), ('intern_id', models.CharField(blank=True, max_length=24, unique=True)), ('domain', models.CharField(blank=True, max_length=80)), ('cohort', models.CharField(blank=True, max_length=80)), ('start_date', models.DateField(blank=True, null=True)), ('end_date', models.DateField(blank=True, null=True)), ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='Task', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('title', models.CharField(max_length=180)), ('description', models.TextField()), ('domain', models.CharField(blank=True, max_length=80)), ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=8)), ('points', models.PositiveIntegerField(default=10)), ('due_date', models.DateField(blank=True, null=True)), ('is_published', models.BooleanField(default=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL))], options={'ordering': ['due_date', '-created_at']}),
        migrations.CreateModel(name='Submission', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('response_text', models.TextField()), ('attachment_url', models.URLField(blank=True)), ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In review'), ('APPROVED', 'Approved'), ('REVISION', 'Needs revision')], default='SUBMITTED', max_length=12)), ('evaluator_feedback', models.TextField(blank=True)), ('awarded_points', models.PositiveIntegerField(default=0)), ('submitted_at', models.DateTimeField(auto_now_add=True)), ('reviewed_at', models.DateTimeField(blank=True, null=True)), ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)), ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='portal.task'))], options={'ordering': ['-submitted_at']}),
        migrations.CreateModel(name='Attendance', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('date', models.DateField(default=django.utils.timezone.localdate)), ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LEAVE', 'Leave')], default='PRESENT', max_length=8)), ('note', models.CharField(blank=True, max_length=240)), ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)), ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_recorded', to=settings.AUTH_USER_MODEL))], options={'ordering': ['-date'], 'unique_together': {('intern', 'date')}}),
    ]
